#!/bin/sh

unset DBUS_SESSION_BUS_ADDRESS
# Uncomment the following two lines for normal desktop:
unset SESSION_MANAGER
#exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
#vncconfig -iconic &

#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
x-window-manager &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1

#日本語入力メソッド iBus
#export GTK_IM_MODULE=ibus
#export XMODIFIERS="@im=ibus"
#export QT_IM_MODULE=ibus
#ibus-daemon -d -x

#/etc/X11/Xsession &
#exec cinnamon-session &
#exec cinnamon-session-cinnamon2d &
exec xfce4-session &

